[package]
name = "wfrs-engine"
description = "Workflow RS - Engine to drive workflows via bpmn diagrams"
version.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
